### ISSUE TITLE
[Feature] Additional Enchantments

### ISSUE THREAD

**Issue by Burgersim** [Burgersim/PGEG#16]
Additional enchantments for Weapons and Tools

Vampirism (Damage dealt --> some healing) 
Poisonous
Randomization (Teleports attacked entity randomly)
Curse of Pain (inflicts damage upon attack on attacker) 
Beheading (chance of looting a head gets higher) 
Expansion (expands mined area of a tool)

**Comment by vladyslav-vasiliev** [comment]
- [x] Vampirism
- [x] Poisonous
- [x] Randomization 
- [x] Curse of Pain
- [x] Beheading 
- [x] Expansion

**Comment by Burgersim** [comment]
Thx a lot, you're fast ^^
